name: endsars
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.4
  apple_sign_in: ^0.1.0
  shared_preferences: ^0.5.12
  flutter_screenutil: ^3.1.1
  page_transition: ^1.1.7+2
  get_it: ^5.0.1
  google_fonts: ^1.1.0
  liquid_swipe: ^1.5.0
  stacked: ^1.7.6
  clay_containers: ^0.2.2
  flutter_neumorphic: ^1.0.4
  firebase_auth: ^0.18.1+2
  firebase_core : ^0.5.0
  url_launcher: ^5.7.2
  android_intent: ^0.3.7+4
  dots_indicator: ^1.2.0
  flutter_signin_button: ^1.1.0
  flutter_shine: ^0.0.5
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.10.0
  firebase_admob: ^0.10.0+2
  material_design_icons_flutter: ^4.0.5755
  random_string: ^2.1.0
  share: ^0.6.5
  cloud_firestore: ^0.14.1+3
  firebase_messaging: ^7.0.3
  readmore: ^1.0.0
  firebase_remote_config: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  

flutter_icons:
    image_path: "assets/img/logo.png"
    android: true
    ios: true
    adaptive_icon_background: "#0000"

flutter:

  uses-material-design: true
  assets:
    - assets/img/
